version: '3'

services:

  db1:
    image: sameersbn/postgresql:9.6-2
    container_name: postgresql9
    env_file: .env/.env_postgresql
    ports:
      - "5432:5432"
    volumes:
      - db_post-accounts:/var/lib/postgresql

  db2:
    image: mysql:8
    container_name: mysql8
    environment:
      - TZ=Europe/Stockholm
    env_file: .env/.env_mysql
    volumes:
      - db_mysql-accounts:/var/lib/mysql

  liquibase:
    image: inki/liquibase:latest
    container_name: liquibase
    tty: true
    depends_on:
      - db2
    links:
      - db2
    volumes:
      - liquibase:/changelogs

volumes:
  db_post-accounts:
  db_mysql-accounts:
  liquibase:
